allure fixes.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,8 +35,13 @@ jobs:
 
       - name: Generate Allure Report
         run: |
-          mkdir -p target/site/allure-maven/
-          mvn allure:report || echo "Allure report generation failed"
+          if [ -d "target/allure-results" ]; then
+            echo "Generating Allure report..."
+            mvn allure:generate target/allure-results -o
+            mvn allure:report || echo "Allure report generation failed"
+          else
+            echo "Skipping Allure report generation: No test results found."
+          fi
 
       - name: Manually Clone Upload-Artifact
         run: |
@@ -48,4 +53,4 @@ jobs:
         uses: ./actions/upload-artifact
         with:
           name: allure-report
-          path: target/site/allure-maven/
+          path: target/allure-results/
